JS TODO List
RokoVarano/JS-TODO_list pull request #4
Opened 2021-06-02 15:28 UTC by RokoVarano

This is a simple list for creating projects and creating events in it to keep track of them.

This project currently features:
- A project form to create projects
- A project list, which displays current projects
- A task form, which displays when a project name is clicked
- A task list, which displays tasks created with their date.
- Every element in either list has a delete button.

2021-06-02 18:58 UTC, MkrtichSargsyan requested changes
## _Status:_ Changes Requested :recycle:

## Hello Emmisteel Okello and Rodrigo Ibaceta Jimenez

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:

## To Highlight :tada:

1. The project is almost done.
3. Your PR has a good title and description.
4. You have descriptive git commit messages.

However, there are some changes that you need to make in order to get your project approved

- [x] Don't disable eslint rules

- [ ] DOM-Manipulation and Logic are in separate modules [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png)

- [x] User can edit the details of a to-do item

- [x] Every To-do item has a description and priority

- [ ] Necessary run common commands like build, development should be in package.json inside `scripts'

      ex  
      "scripts": {
        "dev": "webpack --mode development",
        "build": "webpack --mode production",
        "start": "webpack-dev-server --mode development --open" // optional
      },

- [ ] Use arrow functions instead of the function keyword


<hr>

## OPTIONAL

- [ ] Kindly follow the naming conventions of the file names

- [ ] the forms used to create a project or a todo should have validations, you should not be able to create an empty project/todo

Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-06-02 18:58 UTC, MkrtichSargsyan commented on src/modules/frontend/_bar.js
> +}
use arrow functions instead of the function keyword

2021-06-02 18:58 UTC, MkrtichSargsyan commented on src/modules/frontend/_bar.js
> +}
Use  arrow functions instead of the function keyword

2021-06-02 18:59 UTC, MkrtichSargsyan commented on webpack.config.js
> +  ],
Remove the comments

2021-06-03 18:10 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-03 20:50 UTC, taiwo2 approved these changes
# STATUS:  APPROVED 🎉 
Thanks for implementing the changes
### WELDONE GUYS 👍🏻

2021-06-05 07:26 UTC, merged